# Generated by Django 5.1.15 on 2026-07-24 18:23

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, default=apps.orders.models.generate_unique_order_number, help_text='Unique readable order reference ID', max_length=32, unique=True),
        ),
    ]
