-- TECHNODHA Assessment Task 1: PostgreSQL Relational Schema Export
-- Database: PostgreSQL 15+

BEGIN;

-- 1. Custom User Table (authentication_user)
CREATE TABLE IF NOT EXISTS "authentication_user" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "password" varchar(128) NOT NULL,
    "last_login" timestamp with time zone NULL,
    "is_superuser" boolean NOT NULL,
    "username" varchar(150) NOT NULL UNIQUE,
    "first_name" varchar(150) NOT NULL,
    "last_name" varchar(150) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    "role" varchar(20) NOT NULL DEFAULT 'customer',
    "email" varchar(254) NOT NULL UNIQUE
);

-- 2. Category Table (products_category)
CREATE TABLE IF NOT EXISTS "products_category" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100) NOT NULL UNIQUE,
    "slug" varchar(120) NOT NULL UNIQUE
);

-- 3. Product Table (products_product)
CREATE TABLE IF NOT EXISTS "products_product" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(200) NOT NULL,
    "description" text NOT NULL DEFAULT '',
    "price" numeric(10, 2) NOT NULL,
    "stock_quantity" integer NOT NULL DEFAULT 0,
    "image_url" varchar(500) NULL,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "category_id" bigint NOT NULL REFERENCES "products_category" ("id") ON DELETE PROTECT,
    CONSTRAINT "product_price_non_negative" CHECK ("price" >= 0),
    CONSTRAINT "product_stock_quantity_non_negative" CHECK ("stock_quantity" >= 0)
);

CREATE INDEX IF NOT EXISTS "products_product_name_idx" ON "products_product" ("name");
CREATE INDEX IF NOT EXISTS "products_product_category_id_idx" ON "products_product" ("category_id");

-- 4. Order Table (orders_order)
CREATE TABLE IF NOT EXISTS "orders_order" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "status" varchar(20) NOT NULL DEFAULT 'pending',
    "total_price" numeric(10, 2) NOT NULL DEFAULT 0.00,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "customer_id" bigint NOT NULL REFERENCES "authentication_user" ("id") ON DELETE PROTECT
);

CREATE INDEX IF NOT EXISTS "orders_order_customer_id_idx" ON "orders_order" ("customer_id");
CREATE INDEX IF NOT EXISTS "orders_order_status_idx" ON "orders_order" ("status");

-- 5. OrderItem Table (orders_orderitem)
CREATE TABLE IF NOT EXISTS "orders_orderitem" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "quantity" integer NOT NULL,
    "unit_price_at_purchase" numeric(10, 2) NOT NULL,
    "subtotal" numeric(10, 2) NOT NULL,
    "order_id" bigint NOT NULL REFERENCES "orders_order" ("id") ON DELETE CASCADE,
    "product_id" bigint NOT NULL REFERENCES "products_product" ("id") ON DELETE PROTECT,
    CONSTRAINT "order_item_quantity_positive" CHECK ("quantity" > 0)
);

CREATE INDEX IF NOT EXISTS "orders_orderitem_order_id_idx" ON "orders_orderitem" ("order_id");
CREATE INDEX IF NOT EXISTS "orders_orderitem_product_id_idx" ON "orders_orderitem" ("product_id");

COMMIT;
